export function createImportExportState() {
  return {
    loading: true,
    error: '',
    status: {
      tone: 'idle',
      text: '',
      details: '',
    },
    transfer: {
      active: false,
      label: '',
    },
    localSummary: {
      pages: 0,
      modules: 0,
      collections: 0,
      tabs: 0,
      notes: 0,
      feedSources: 0,
      savedFeedItems: 0,
      assets: 0,
    },
    exportState: null,
    remoteSettings: null,
    remoteDraft: null,
    compareInspection: null,
    remotePullPreview: null,
    remotePreviewSummary: null,
    remoteHealth: null,
    remoteActivity: '',
    remoteWarnings: [],
    deepCheckReport: null,
    deepCheckSelectedUnusedAssetIds: [],
    resetOptionsOpen: false,
    busy: {
      remoteConfig: false,
      remoteCheck: false,
      remotePreview: false,
      remotePush: false,
      remotePull: false,
      remoteDownload: false,
      localExport: false,
      localImport: false,
      deepCheck: false,
      resetDatabase: false,
    },
  }
}
